name:                neo4j-test-stack
version:             0.1.0.0
license:             BSD3
author:              "Nolan"
maintainer:          "nolane16@gmail.com"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/test#readme>

dependencies:
- base >= 4.9 && < 4.12
- data-default >= 0.7 && < 0.8
- hasbolt >= 0.1.3 && < 0.1.4
- text >= 1.2.3 && < 1.2.4
- containers >=0.5.7.1 && <0.6 

library:
  source-dirs: src

executables:
  neo4j-test-stack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - neo4j-test-stack
